<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $seller = User::where('role', 'seller')->first() ?? User::where('email', 'seller@example.com')->first();

        if (!$seller) {
            return;
        }

        $categories = [
            'pakaian-pria'   => Category::firstOrCreate(['name' => 'Pakaian Pria'], ['slug' => 'pakaian-pria']),
            'pakaian-wanita' => Category::firstOrCreate(['name' => 'Pakaian Wanita'], ['slug' => 'pakaian-wanita']),
            'aksesoris'      => Category::firstOrCreate(['name' => 'Aksesoris'], ['slug' => 'aksesoris']),
        ];

        $products = [
            // ================= PAKAIAN PRIA (10 PRODUK) =================
            [
                'seller_id'   => $seller->id,
                'name'        => 'Esensi Struktural',
                'slug'        => Str::slug('Esensi Struktural'),
                'category_id' => $categories['pakaian-pria']->id,
                'price'       => 4500000,
                'description' => 'Ditenun dari linen murni dan wol halus, koleksi ini menampilkan keanggunan minimalis dengan presisi arsitektural.',
                'thumbnail'   => 'products/esensi-struktural.jpg',
                'file_path'   => 'products/esensi-struktural.pdf',
                'status'      => 'approved',
            ],
            [
                'seller_id'   => $seller->id,
                'name'        => 'Mantel Musim Dingin',
                'slug'        => Str::slug('Mantel Musim Dingin'),
                'category_id' => $categories['pakaian-pria']->id,
                'price'       => 8200000,
                'description' => 'Dirancang untuk kehangatan optimal tanpa mengorbankan siluet tegas.',
                'thumbnail'   => 'products/mantel-musim-dingin.jpg',
                'file_path'   => 'products/mantel-musim-dingin.pdf',
                'status'      => 'approved',
            ],
            [
                'seller_id'   => $seller->id,
                'name'        => 'Kemeja Linen Cutaway',
                'slug'        => Str::slug('Kemeja Linen Cutaway'),
                'category_id' => $categories['pakaian-pria']->id,
                'price'       => 2100000,
                'description' => 'Potongan kemeja santai namun tetap terstruktur rapi untuk tampilan profesional.',
                'thumbnail'   => 'products/kemeja-linen.jpg',
                'file_path'   => 'products/kemeja-linen.pdf',
                'status'      => 'approved',
            ],
            [
                'seller_id'   => $seller->id,
                'name'        => 'Jas Wool Tailored Executive',
                'slug'        => Str::slug('Jas Wool Tailored Executive'),
                'category_id' => $categories['pakaian-pria']->id,
                'price'       => 12500000,
                'description' => 'Setelan jas wol Italia pilihan dengan jahitan tangan berlapis furing halus.',
                'thumbnail'   => 'products/jas-wool-tailored.jpg',
                'file_path'   => 'products/jas-wool-tailored.pdf',
                'status'      => 'approved',
            ],
            [
                'seller_id'   => $seller->id,
                'name'        => 'Jaket Suede Minimalis',
                'slug'        => Str::slug('Jaket Suede Minimalis'),
                'category_id' => $categories['pakaian-pria']->id,
                'price'       => 6800000,
                'description' => 'Jaket kulit suede premium dengan potongan ringkas dan ritsleting tersembunyi.',
                'thumbnail'   => 'products/jaket-suede.jpg',
                'file_path'   => 'products/jaket-suede.pdf',
                'status'      => 'approved',
            ],
            [
                'seller_id'   => $seller->id,
                'name'        => 'Celana Pleated Trouser',
                'slug'        => Str::slug('Celana Pleated Trouser'),
                'category_id' => $categories['pakaian-pria']->id,
                'price'       => 2700000,
                'description' => 'Celana bahan berlipit ganda yang memberikan ruang gerak nyaman dan jatuh yang sempurna.',
                'thumbnail'   => 'products/celana-pleated.jpg',
                'file_path'   => 'products/celana-pleated.pdf',
                'status'      => 'approved',
            ],
            [
                'seller_id'   => $seller->id,
                'name'        => 'Sweater Cashmere Crewneck',
                'slug'        => Str::slug('Sweater Cashmere Crewneck'),
                'category_id' => $categories['pakaian-pria']->id,
                'price'       => 3900000,
                'description' => 'Rajutan kasmir super lembut dengan daya tahan tinggi dan kenyamanan maksimal.',
                'thumbnail'   => 'products/sweater-cashmere.jpg',
                'file_path'   => 'products/sweater-cashmere.pdf',
                'status'      => 'approved',
            ],
            [
                'seller_id'   => $seller->id,
                'name'        => 'Kemeja Oxford Oversized',
                'slug'        => Str::slug('Kemeja Oxford Oversized'),
                'category_id' => $categories['pakaian-pria']->id,
                'price'       => 1850000,
                'description' => 'Kemeja Oxford klasik dengan potongan agak longgar untuk gaya modern kasual.',
                'thumbnail'   => 'products/kemeja-oxford.jpg',
                'file_path'   => 'products/kemeja-oxford.pdf',
                'status'      => 'approved',
            ],
            [
                'seller_id'   => $seller->id,
                'name'        => 'Parka Technical Weatherproof',
                'slug'        => Str::slug('Parka Technical Weatherproof'),
                'category_id' => $categories['pakaian-pria']->id,
                'price'       => 7400000,
                'description' => 'Parka tahan angin dan air dengan desain utilitarian namun tetap bersih.',
                'thumbnail'   => 'products/parka-technical.jpg',
                'file_path'   => 'products/parka-technical.pdf',
                'status'      => 'approved',
            ],
            [
                'seller_id'   => $seller->id,
                'name'        => 'Cardigan Chunky Knit',
                'slug'        => Str::slug('Cardigan Chunky Knit'),
                'category_id' => $categories['pakaian-pria']->id,
                'price'       => 3200000,
                'description' => 'Luaran rajut tebal bertekstur tinggi dengan kancing tanduk asli.',
                'thumbnail'   => 'products/cardigan-knit.jpg',
                'file_path'   => 'products/cardigan-knit.pdf',
                'status'      => 'approved',
            ],

            // ================= PAKAIAN WANITA (10 PRODUK) =================
            [
                'seller_id'   => $seller->id,
                'name'        => 'Kain Premium',
                'slug'        => Str::slug('Kain Premium'),
                'category_id' => $categories['pakaian-wanita']->id,
                'price'       => 800000,
                'description' => 'Pilihan serat organik terbaik untuk kenyamanan tak tertandingi sepanjang hari.',
                'thumbnail'   => 'products/kain-premium.jpg',
                'file_path'   => 'products/kain-premium.pdf',
                'status'      => 'approved',
            ],
            [
                'seller_id'   => $seller->id,
                'name'        => 'Gaun Sutra Minimalis',
                'slug'        => Str::slug('Gaun Sutra Minimalis'),
                'category_id' => $categories['pakaian-wanita']->id,
                'price'       => 6400000,
                'description' => 'Gaun terusan berbahan sutra murni dengan potongan drape yang elegan.',
                'thumbnail'   => 'products/gaun-sutra.jpg',
                'file_path'   => 'products/gaun-sutra.pdf',
                'status'      => 'approved',
            ],
            [
                'seller_id'   => $seller->id,
                'name'        => 'Blazer Structured Double-Breasted',
                'slug'        => Str::slug('Blazer Structured Double-Breasted'),
                'category_id' => $categories['pakaian-wanita']->id,
                'price'       => 7800000,
                'description' => 'Blazer dengan bahu tegas dan siluet pinggang berstruktur untuk tampilan profesional berkelas.',
                'thumbnail'   => 'products/blazer-structured.jpg',
                'file_path'   => 'products/blazer-structured.pdf',
                'status'      => 'approved',
            ],
            [
                'seller_id'   => $seller->id,
                'name'        => 'Gaun Malam Wrap Silk',
                'slug'        => Str::slug('Gaun Malam Wrap Silk'),
                'category_id' => $categories['pakaian-wanita']->id,
                'price'       => 9200000,
                'description' => 'Gaun malam model wrap dari bahan sutra mulberry yang berkilau lembut di bawah cahaya.',
                'thumbnail'   => 'products/gaun-malam-wrap.jpg',
                'file_path'   => 'products/gaun-malam-wrap.pdf',
                'status'      => 'approved',
            ],
            [
                'seller_id'   => $seller->id,
                'name'        => 'Blouse High-Neck Pleated',
                'slug'        => Str::slug('Blouse High-Neck Pleated'),
                'category_id' => $categories['pakaian-wanita']->id,
                'price'       => 2400000,
                'description' => 'Atasan leher tinggi dengan detail lipit halus pada bagian dada dan lengan.',
                'thumbnail'   => 'products/blouse-pleated.jpg',
                'file_path'   => 'products/blouse-pleated.pdf',
                'status'      => 'approved',
            ],
            [
                'seller_id'   => $seller->id,
                'name'        => 'Celana Wide-Leg Wool',
                'slug'        => Str::slug('Celana Wide-Leg Wool'),
                'category_id' => $categories['pakaian-wanita']->id,
                'price'       => 3100000,
                'description' => 'Celana kaki lebar bahan campuran wol ringan yang memberi kesan jenjang.',
                'thumbnail'   => 'products/celana-wide-leg.jpg',
                'file_path'   => 'products/celana-wide-leg.pdf',
                'status'      => 'approved',
            ],
            [
                'seller_id'   => $seller->id,
                'name'        => 'Trench Coat Classic Beige',
                'slug'        => Str::slug('Trench Coat Classic Beige'),
                'category_id' => $categories['pakaian-wanita']->id,
                'price'       => 11000000,
                'description' => 'Mantel luaran klasik dengan sabuk ikat pinggang dan kancing kontras.',
                'thumbnail'   => 'products/trench-coat.jpg',
                'file_path'   => 'products/trench-coat.pdf',
                'status'      => 'approved',
            ],
            [
                'seller_id'   => $seller->id,
                'name'        => 'Rok Midi Satin Asimetris',
                'slug'        => Str::slug('Rok Midi Satin Asimetris'),
                'category_id' => $categories['pakaian-wanita']->id,
                'price'       => 2900000,
                'description' => 'Rok midi potongan asimetris dari kain satin tebal yang mengalir indah saat melangkah.',
                'thumbnail'   => 'products/rok-midi-satin.jpg',
                'file_path'   => 'products/rok-midi-satin.pdf',
                'status'      => 'approved',
            ],
            [
                'seller_id'   => $seller->id,
                'name'        => 'Cardigan Cashmere Soft',
                'slug'        => Str::slug('Cardigan Cashmere Soft'),
                'category_id' => $categories['pakaian-wanita']->id,
                'price'       => 4200000,
                'description' => 'Luaran kasmir rajut tangan yang ringan namun memberikan kehangatan sempurna.',
                'thumbnail'   => 'products/cardigan-soft.jpg',
                'file_path'   => 'products/cardigan-cashmere.pdf',
                'status'      => 'approved',
            ],
            [
                'seller_id'   => $seller->id,
                'name'        => 'Outer Linen Layered',
                'slug'        => Str::slug('Outer Linen Layered'),
                'category_id' => $categories['pakaian-wanita']->id,
                'price'       => 3600000,
                'description' => 'Luaran berlapis dari bahan linen organik yang sejuk dan cocok untuk gaya bertumpuk.',
                'thumbnail'   => 'products/outer-linen.jpg',
                'file_path'   => 'products/outer-linen.pdf',
                'status'      => 'approved',
            ],

            // ================= AKSESORIS (10 PRODUK) =================
            [
                'seller_id'   => $seller->id,
                'name'        => 'Pelengkap Tampilan',
                'slug'        => Str::slug('Pelengkap Tampilan'),
                'category_id' => $categories['aksesoris']->id,
                'price'       => 3100000,
                'description' => 'Sentuhan akhir yang mendefinisikan gaya dengan keahlian pengrajin tingkat tinggi.',
                'thumbnail'   => 'products/pelengkap-tampilan.jpg',
                'file_path'   => 'products/pelengkap-tampilan.pdf',
                'status'      => 'approved',
            ],
            [
                'seller_id'   => $seller->id,
                'name'        => 'Sabuk Kulit Artisan',
                'slug'        => Str::slug('Sabuk Kulit Artisan'),
                'category_id' => $categories['aksesoris']->id,
                'price'       => 1500000,
                'description' => 'Dibuat dari kulit nabati berkualitas dengan gesper kuningan buatan tangan.',
                'thumbnail'   => 'products/sabuk-kulit.jpg',
                'file_path'   => 'products/sabuk-kulit.pdf',
                'status'      => 'approved',
            ],
            [
                'seller_id'   => $seller->id,
                'name'        => 'Syal Silk Print Limited',
                'slug'        => Str::slug('Syal Silk Print Limited'),
                'category_id' => $categories['aksesoris']->id,
                'price'       => 1900000,
                'description' => 'Syal leher dari serat sutra murni dengan motif grafis abstrak edisi terbatas.',
                'thumbnail'   => 'products/syal-silk.jpg',
                'file_path'   => 'products/syal-silk.pdf',
                'status'      => 'approved',
            ],
            [
                'seller_id'   => $seller->id,
                'name'        => 'Tas Genggam Leather Clutch',
                'slug'        => Str::slug('Tas Genggam Leather Clutch'),
                'category_id' => $categories['aksesoris']->id,
                'price'       => 4800000,
                'description' => 'Tas tangan kulit asli dengan kompartemen rapi untuk esensial harian atau pesta.',
                'thumbnail'   => 'products/leather-clutch.jpg',
                'file_path'   => 'products/leather-clutch.pdf',
                'status'      => 'approved',
            ],
            [
                'seller_id'   => $seller->id,
                'name'        => 'Topi Wool Fedora',
                'slug'        => Str::slug('Topi Wool Fedora'),
                'category_id' => $categories['aksesoris']->id,
                'price'       => 1200000,
                'description' => 'Topi felt wol dengan pita kulit minimalis di sekeliling mahkota topi.',
                'thumbnail'   => 'products/topi-fedora.jpg',
                'file_path'   => 'products/topi-fedora.pdf',
                'status'      => 'approved',
            ],
            [
                'seller_id'   => $seller->id,
                'name'        => 'Kacamata Hitam Acetate Frame',
                'slug'        => Str::slug('Kacamata Hitam Acetate Frame'),
                'category_id' => $categories['aksesoris']->id,
                'price'       => 2600000,
                'description' => 'Frame buatan tangan dari bahan asetat organik dengan lensa pelindung UV400.',
                'thumbnail'   => 'products/kacamata-acetate.jpg',
                'file_path'   => 'products/kacamata-acetate.pdf',
                'status'      => 'approved',
            ],
            [
                'seller_id'   => $seller->id,
                'name'        => 'Dompet Kulit Cardholder',
                'slug'        => Str::slug('Dompet Kulit Cardholder'),
                'category_id' => $categories['aksesoris']->id,
                'price'       => 950000,
                'description' => 'Dompet kartu ringkas dengan 6 slot dan kompartemen tengah untuk uang tunai.',
                'thumbnail'   => 'products/dompet-cardholder.jpg',
                'file_path'   => 'products/dompet-cardholder.pdf',
                'status'      => 'approved',
            ],
            [
                'seller_id'   => $seller->id,
                'name'        => 'Jam Tangan Leather Strap Minimal',
                'slug'        => Str::slug('Jam Tangan Leather Strap Minimal'),
                'category_id' => $categories['aksesoris']->id,
                'price'       => 8500000,
                'description' => 'Jam tangan analog movement Jepang dengan dial bersih dan tali kulit sapi asli.',
                'thumbnail'   => 'products/jam-tangan-leather.jpg',
                'file_path'   => 'products/jam-tangan-leather.pdf',
                'status'      => 'approved',
            ],
            [
                'seller_id'   => $seller->id,
                'name'        => 'Sarung Tangan Kulit Cashmere',
                'slug'        => Str::slug('Sarung Tangan Kulit Cashmere'),
                'category_id' => $categories['aksesoris']->id,
                'price'       => 1750000,
                'description' => 'Sarung tangan kulit lembut dengan lapisan dalam kasmir untuk kehangatan ekstra.',
                'thumbnail'   => 'products/sarung-tangan-kulit.jpg',
                'file_path'   => 'products/sarung-tangan-kulit.pdf',
                'status'      => 'approved',
            ],
            [
                'seller_id'   => $seller->id,
                'name'        => 'Tas Tote Canvas & Leather',
                'slug'        => Str::slug('Tas Tote Canvas & Leather'),
                'category_id' => $categories['aksesoris']->id,
                'price'       => 5200000,
                'description' => 'Tas jinjing kokoh perpaduan kanvas tebal dan pinggiran kulit asli berketahanan tinggi.',
                'thumbnail'   => 'products/tote-canvas-leather.jpg',
                'file_path'   => 'products/tote-canvas-leather.pdf',
                'status'      => 'approved',
            ],
        ];

foreach ($products as $prod) {
    Product::updateOrCreate(
        ['name' => $prod['name']], // Acuan pencarian berdasarkan nama
        $prod                      // Data yang di-update (termasuk thumbnail & file_path baru)
    );
}
    }
}